spring.application.name=demo

server.port=8080
# Cấu hình Supabase
supabase.url=https://znfxhbrkabxenuzrcogd.supabase.co/rest/v1
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZnhoYnJrYWJ4ZW51enJjb2dkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTQ0Mjk4NSwiZXhwIjoyMDkxMDE4OTg1fQ.qNtUEq0HebqEs6tHrWT6Ghj94-UOb5dshIWAvWB8r6Y
supabase.api-key=${supabase.key}
# Cấu hình MQTT
mqtt.broker=tcp://broker.hivemq.com:1883
mqtt.topic.data=ptit/test/request
mqtt.topic.control=ptit/device/control

# Email configuration (cấu hình Gmail - thay bằng email thật)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Người nhận alert (thay bằng email thật)
alert.email.to=ncmongaming@gmail.com
