spring.application.name=backend
server.port=8080
supabase.url=${SUPABASE_URL:https://znfxhbrkabxenuzrcogd.supabase.co/rest/v1}
supabase.api-key=${SUPABASE_API_KEY:sb_secret_NXFJy_AuCYhqJmmJadDKNA_I7N91qFu}
supabase.key=${SUPABASE_API_KEY:sb_secret_NXFJy_AuCYhqJmmJadDKNA_I7N91qFu}
mqtt.broker=${MQTT_BROKER:tcp://broker.hivemq.com:1883}
mqtt.topic.data=${MQTT_TOPIC_DATA:ptit/test/request}
mqtt.topic.control=${MQTT_TOPIC_CONTROL:ptit/device/control}
spring.web.resources.static-locations=classpath:/static/,file:./web/
